language: dart

dart:
  - "2.0.0"
  - "2.1.1"
  - stable
  - dev

matrix:
  allow_failures:
    - dart: dev

dart_task:
  - test
  - dartfmt
  - dartanalyzer: --fatal-warnings .

cache:
  directories:
    - $HOME/.pub-cache
