# https://www.dartlang.org/guides/language/analysis-options
# Use Google internal analysis options from
# https://pub.dartlang.org/packages/pedantic
import: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: false

# Source of linter options:
# http://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
    - control_flow_in_finally
    - empty_statements
    - throw_in_finally
