name: math_expressions
version: 1.1.1
author: Frederik Leonhardt <frederik.leonhardt@gmail.com>
homepage: https://github.com/fkleon/math-expressions
description: >-
  A library for parsing and evaluating mathematical expressions, supporting real
  numbers, vectors, and basic interval arithmetic.

dependencies:
  vector_math: ^2.0.0

dev_dependencies:
  pedantic: ^1.4.0
  test: ^1.3.0

environment:
  sdk: '>=2.1.1 <3.0.0'
