name: math_expressions
version: 1.0.0
author: Frederik Leonhardt <frederik.leonhardt@gmail.com>
description: A library for evaluating mathematical expressions.
homepage: https://github.com/fkleon/math-expressions
documentation: http://www.dartdocs.org/documentation/math_expressions/latest
dependencies:
  vector_math: ^2.0.0
  dart2_constant: ^1.0.1
dev_dependencies:
  test: '>=0.12.34 <2.0.0'
environment:
  sdk: '>=1.24.0 <3.0.0'
