name: math_expressions
version: 0.1.0
author: Frederik Leonhardt <frederik.leonhardt@gmail.com>
description: A math library for parsing and evaluating expressions in real, interval and vector contexts. Also supports simplification and differentiation.
homepage: https://github.com/fkleon/math-expressions
documentation: http://fkleon.github.io/math-expressions
dependencies:
  vector_math: '>=1.3.5 <1.5.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.11.0'
  matcher: '>=0.10.0 <0.11.0'
environment:
  sdk: '>=0.8.10+6 <2.0.0'
