name: math_expressions
version: 1.1.1-dev
author: Frederik Leonhardt <frederik.leonhardt@gmail.com>
description: A library for evaluating mathematical expressions.
homepage: https://github.com/fkleon/math-expressions
dependencies:
  vector_math: ^2.0.0
dev_dependencies:
  pedantic: '>=1.4.0 <2.0.0'
  test: '>=1.3.0 <2.0.0'
environment:
  sdk: '>=2.0.0 <3.0.0'
