name: math_expressions
version: 0.0.1
author: Frederik Leonhardt <frederik.leonhardt@gmail.com>
description: A math library supporting REAL, INTERVAL and VECTOR evaluations of arbitrary expressions.
homepage: https://github.com/fkleon/math_expressions
dependencies:
  vector_math: ">=1.3.5 <1.4.0"
dev_dependencies:
  unittest: any
  benchmark_harness: any